/**
 * Preset diagram themes for the "Theme" dropdown (next to the layout dropdown).
 *
 * Each preset is a native mermaid `themeVariables` palette layered on the `base`
 * theme — the only built-in theme that honors `themeVariables` overrides.
 * Selecting one injects `theme` + `themeVariables` into the YAML config (the
 * single source of truth) via `setThemeInYaml`, which both retunes every diagram
 * render and recolors the app chrome (see `applyThemeToSite`).
 *
 * The 15 palettes below mirror the popular editor color schemes (zinc, Tokyo
 * Night, Catppuccin, Nord, Dracula, GitHub, Solarized, One Dark).
 */

export interface ThemePreset {
  /** Stable id used as the Select value and for round-trip matching. */
  value: string
  /** Human-readable label shown in the dropdown. */
  label: string
  /** Always `base` — the only theme that honors `themeVariables`. */
  theme: string
  /** The mermaid theme variables that define the palette. */
  themeVariables: Record<string, string>
}

export const THEME_PRESETS: readonly ThemePreset[] = [
  {
    value: 'zinc-light',
    label: 'Zinc Light',
    theme: 'base',
    themeVariables: {
      background: '#FFFFFF',
      primaryColor: '#F4F4F5',
      primaryTextColor: '#27272A',
      primaryBorderColor: '#A1A1AA',
      lineColor: '#71717A',
      secondaryColor: '#E4E4E7',
      tertiaryColor: '#D4D4D8',
      mainBkg: '#F4F4F5',
      nodeBorder: '#A1A1AA',
      clusterBkg: '#E4E4E7',
      clusterBorder: '#A1A1AA',
      edgeLabelBackground: '#FFFFFF',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#F4F4F5',
      actorBorder: '#A1A1AA',
      signalColor: '#27272A',
      signalTextColor: '#27272A',
      labelBoxBkgColor: '#F4F4F5',
      labelBoxBorderColor: '#A1A1AA',
      noteBkgColor: '#FEF08A',
      noteTextColor: '#27272A',
    },
  },
  {
    value: 'zinc-dark',
    label: 'Zinc Dark',
    theme: 'base',
    themeVariables: {
      background: '#18181B',
      primaryColor: '#27272A',
      primaryTextColor: '#FAFAFA',
      primaryBorderColor: '#52525B',
      lineColor: '#71717A',
      secondaryColor: '#3F3F46',
      tertiaryColor: '#52525B',
      mainBkg: '#27272A',
      nodeBorder: '#52525B',
      clusterBkg: '#3F3F46',
      clusterBorder: '#52525B',
      edgeLabelBackground: '#18181B',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#27272A',
      actorBorder: '#52525B',
      signalColor: '#FAFAFA',
      signalTextColor: '#FAFAFA',
      labelBoxBkgColor: '#27272A',
      labelBoxBorderColor: '#52525B',
      noteBkgColor: '#FDE68A',
      noteTextColor: '#18181B',
    },
  },
  {
    value: 'tokyo-night',
    label: 'Tokyo Night',
    theme: 'base',
    themeVariables: {
      background: '#1a1b26',
      primaryColor: '#24283b',
      primaryTextColor: '#a9b1d6',
      primaryBorderColor: '#7aa2f7',
      lineColor: '#3d59a1',
      secondaryColor: '#414868',
      tertiaryColor: '#565f89',
      mainBkg: '#24283b',
      nodeBorder: '#7aa2f7',
      clusterBkg: '#1f2335',
      clusterBorder: '#3d59a1',
      edgeLabelBackground: '#1a1b26',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#24283b',
      actorBorder: '#7aa2f7',
      signalColor: '#a9b1d6',
      signalTextColor: '#a9b1d6',
      labelBoxBkgColor: '#24283b',
      labelBoxBorderColor: '#3d59a1',
      noteBkgColor: '#e0af68',
      noteTextColor: '#1a1b26',
    },
  },
  {
    value: 'tokyo-night-storm',
    label: 'Tokyo Night Storm',
    theme: 'base',
    themeVariables: {
      background: '#24283b',
      primaryColor: '#1f2335',
      primaryTextColor: '#a9b1d6',
      primaryBorderColor: '#7aa2f7',
      lineColor: '#3d59a1',
      secondaryColor: '#414868',
      tertiaryColor: '#565f89',
      mainBkg: '#1f2335',
      nodeBorder: '#7aa2f7',
      clusterBkg: '#292e42',
      clusterBorder: '#3d59a1',
      edgeLabelBackground: '#24283b',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#1f2335',
      actorBorder: '#7aa2f7',
      signalColor: '#a9b1d6',
      signalTextColor: '#a9b1d6',
      labelBoxBkgColor: '#1f2335',
      labelBoxBorderColor: '#3d59a1',
      noteBkgColor: '#e0af68',
      noteTextColor: '#24283b',
    },
  },
  {
    value: 'tokyo-night-light',
    label: 'Tokyo Night Light',
    theme: 'base',
    themeVariables: {
      background: '#d5d6db',
      primaryColor: '#e9e9ec',
      primaryTextColor: '#343b58',
      primaryBorderColor: '#34548a',
      lineColor: '#34548a',
      secondaryColor: '#cbccd1',
      tertiaryColor: '#9699a3',
      mainBkg: '#e9e9ec',
      nodeBorder: '#34548a',
      clusterBkg: '#cbccd1',
      clusterBorder: '#34548a',
      edgeLabelBackground: '#d5d6db',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#e9e9ec',
      actorBorder: '#34548a',
      signalColor: '#343b58',
      signalTextColor: '#343b58',
      labelBoxBkgColor: '#e9e9ec',
      labelBoxBorderColor: '#34548a',
      noteBkgColor: '#e6c78b',
      noteTextColor: '#343b58',
    },
  },
  {
    value: 'catppuccin-mocha',
    label: 'Catppuccin Mocha',
    theme: 'base',
    themeVariables: {
      background: '#1e1e2e',
      primaryColor: '#313244',
      primaryTextColor: '#cdd6f4',
      primaryBorderColor: '#cba6f7',
      lineColor: '#585b70',
      secondaryColor: '#45475a',
      tertiaryColor: '#6c7086',
      mainBkg: '#313244',
      nodeBorder: '#cba6f7',
      clusterBkg: '#181825',
      clusterBorder: '#585b70',
      edgeLabelBackground: '#1e1e2e',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#313244',
      actorBorder: '#cba6f7',
      signalColor: '#cdd6f4',
      signalTextColor: '#cdd6f4',
      labelBoxBkgColor: '#313244',
      labelBoxBorderColor: '#585b70',
      noteBkgColor: '#f9e2af',
      noteTextColor: '#1e1e2e',
    },
  },
  {
    value: 'catppuccin-latte',
    label: 'Catppuccin Latte',
    theme: 'base',
    themeVariables: {
      background: '#eff1f5',
      primaryColor: '#e6e9ef',
      primaryTextColor: '#4c4f69',
      primaryBorderColor: '#8839ef',
      lineColor: '#9ca0b0',
      secondaryColor: '#ccd0da',
      tertiaryColor: '#bcc0cc',
      mainBkg: '#e6e9ef',
      nodeBorder: '#8839ef',
      clusterBkg: '#ccd0da',
      clusterBorder: '#9ca0b0',
      edgeLabelBackground: '#eff1f5',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#e6e9ef',
      actorBorder: '#8839ef',
      signalColor: '#4c4f69',
      signalTextColor: '#4c4f69',
      labelBoxBkgColor: '#e6e9ef',
      labelBoxBorderColor: '#9ca0b0',
      noteBkgColor: '#f9e2af',
      noteTextColor: '#4c4f69',
    },
  },
  {
    value: 'nord',
    label: 'Nord',
    theme: 'base',
    themeVariables: {
      background: '#2e3440',
      primaryColor: '#3b4252',
      primaryTextColor: '#d8dee9',
      primaryBorderColor: '#88c0d0',
      lineColor: '#4c566a',
      secondaryColor: '#434c5e',
      tertiaryColor: '#4c566a',
      mainBkg: '#3b4252',
      nodeBorder: '#88c0d0',
      clusterBkg: '#434c5e',
      clusterBorder: '#4c566a',
      edgeLabelBackground: '#2e3440',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#3b4252',
      actorBorder: '#88c0d0',
      signalColor: '#d8dee9',
      signalTextColor: '#d8dee9',
      labelBoxBkgColor: '#3b4252',
      labelBoxBorderColor: '#4c566a',
      noteBkgColor: '#ebcb8b',
      noteTextColor: '#2e3440',
    },
  },
  {
    value: 'nord-light',
    label: 'Nord Light',
    theme: 'base',
    themeVariables: {
      primaryColor: '#e5e9f0',
      primaryTextColor: '#2e3440',
      primaryBorderColor: '#5e81ac',
      lineColor: '#5e81ac',
      secondaryColor: '#eceff4',
      tertiaryColor: '#d8dee9',
      background: '#eceff4',
      mainBkg: '#e5e9f0',
      nodeBorder: '#5e81ac',
      clusterBkg: '#d8dee9',
      clusterBorder: '#4c566a',
      edgeLabelBackground: '#eceff4',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#e5e9f0',
      actorBorder: '#5e81ac',
      signalColor: '#2e3440',
      signalTextColor: '#2e3440',
      labelBoxBkgColor: '#e5e9f0',
      labelBoxBorderColor: '#4c566a',
      noteBkgColor: '#ebcb8b',
      noteTextColor: '#2e3440',
    },
  },
  {
    value: 'dracula',
    label: 'Dracula',
    theme: 'base',
    themeVariables: {
      background: '#282a36',
      primaryColor: '#44475a',
      primaryTextColor: '#f8f8f2',
      primaryBorderColor: '#bd93f9',
      lineColor: '#6272a4',
      secondaryColor: '#383a4c',
      tertiaryColor: '#6272a4',
      mainBkg: '#44475a',
      nodeBorder: '#bd93f9',
      clusterBkg: '#343746',
      clusterBorder: '#6272a4',
      edgeLabelBackground: '#282a36',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#44475a',
      actorBorder: '#bd93f9',
      signalColor: '#f8f8f2',
      signalTextColor: '#f8f8f2',
      labelBoxBkgColor: '#44475a',
      labelBoxBorderColor: '#6272a4',
      noteBkgColor: '#f1fa8c',
      noteTextColor: '#282a36',
    },
  },
  {
    value: 'github-light',
    label: 'GitHub Light',
    theme: 'base',
    themeVariables: {
      background: '#ffffff',
      primaryColor: '#f6f8fa',
      primaryTextColor: '#1f2328',
      primaryBorderColor: '#0969da',
      lineColor: '#d1d9e0',
      secondaryColor: '#eaeef2',
      tertiaryColor: '#d1d9e0',
      mainBkg: '#f6f8fa',
      nodeBorder: '#0969da',
      clusterBkg: '#eaeef2',
      clusterBorder: '#d1d9e0',
      edgeLabelBackground: '#ffffff',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#f6f8fa',
      actorBorder: '#0969da',
      signalColor: '#1f2328',
      signalTextColor: '#1f2328',
      labelBoxBkgColor: '#f6f8fa',
      labelBoxBorderColor: '#d1d9e0',
      noteBkgColor: '#fff8c5',
      noteTextColor: '#1f2328',
    },
  },
  {
    value: 'github-dark',
    label: 'GitHub Dark',
    theme: 'base',
    themeVariables: {
      background: '#0d1117',
      primaryColor: '#161b22',
      primaryTextColor: '#e6edf3',
      primaryBorderColor: '#4493f8',
      lineColor: '#3d444d',
      secondaryColor: '#21262d',
      tertiaryColor: '#3d444d',
      mainBkg: '#161b22',
      nodeBorder: '#4493f8',
      clusterBkg: '#21262d',
      clusterBorder: '#3d444d',
      edgeLabelBackground: '#0d1117',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#161b22',
      actorBorder: '#4493f8',
      signalColor: '#e6edf3',
      signalTextColor: '#e6edf3',
      labelBoxBkgColor: '#161b22',
      labelBoxBorderColor: '#3d444d',
      noteBkgColor: '#d29922',
      noteTextColor: '#0d1117',
    },
  },
  {
    value: 'solarized-light',
    label: 'Solarized Light',
    theme: 'base',
    themeVariables: {
      background: '#fdf6e3',
      primaryColor: '#eee8d5',
      primaryTextColor: '#657b83',
      primaryBorderColor: '#268bd2',
      lineColor: '#93a1a1',
      secondaryColor: '#eee8d5',
      tertiaryColor: '#93a1a1',
      mainBkg: '#eee8d5',
      nodeBorder: '#268bd2',
      clusterBkg: '#eee8d5',
      clusterBorder: '#93a1a1',
      edgeLabelBackground: '#fdf6e3',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#eee8d5',
      actorBorder: '#268bd2',
      signalColor: '#657b83',
      signalTextColor: '#657b83',
      labelBoxBkgColor: '#eee8d5',
      labelBoxBorderColor: '#93a1a1',
      noteBkgColor: '#b58900',
      noteTextColor: '#fdf6e3',
    },
  },
  {
    value: 'solarized-dark',
    label: 'Solarized Dark',
    theme: 'base',
    themeVariables: {
      background: '#002b36',
      primaryColor: '#073642',
      primaryTextColor: '#839496',
      primaryBorderColor: '#268bd2',
      lineColor: '#586e75',
      secondaryColor: '#073642',
      tertiaryColor: '#586e75',
      mainBkg: '#073642',
      nodeBorder: '#268bd2',
      clusterBkg: '#073642',
      clusterBorder: '#586e75',
      edgeLabelBackground: '#002b36',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#073642',
      actorBorder: '#268bd2',
      signalColor: '#839496',
      signalTextColor: '#839496',
      labelBoxBkgColor: '#073642',
      labelBoxBorderColor: '#586e75',
      noteBkgColor: '#b58900',
      noteTextColor: '#002b36',
    },
  },
  {
    value: 'one-dark',
    label: 'One Dark',
    theme: 'base',
    themeVariables: {
      background: '#282c34',
      primaryColor: '#2c313a',
      primaryTextColor: '#abb2bf',
      primaryBorderColor: '#c678dd',
      lineColor: '#4b5263',
      secondaryColor: '#3e4451',
      tertiaryColor: '#4b5263',
      mainBkg: '#2c313a',
      nodeBorder: '#c678dd',
      clusterBkg: '#21252b',
      clusterBorder: '#4b5263',
      edgeLabelBackground: '#282c34',
      fontFamily: 'JetBrains Mono',
      actorBkg: '#2c313a',
      actorBorder: '#c678dd',
      signalColor: '#abb2bf',
      signalTextColor: '#abb2bf',
      labelBoxBkgColor: '#2c313a',
      labelBoxBorderColor: '#4b5263',
      noteBkgColor: '#e5c07b',
      noteTextColor: '#282c34',
    },
  },
]
